#!/usr/bin/env bash
# Generate demo/credentials.yaml from your ALREADY-AUTHENTICATED cloud CLIs.
#
# Run this after logging in to each cloud (any platform you skip is left blank with
# a warning, and preflight will flag it):
#   gcloud auth login && gcloud config set project <id>
#   oci setup bootstrap          # browser auth; auto-creates + uploads the api key
#   aws configure                # after creating one IAM access key
#
# It fills only the ids (project / compartment / region) and leaves the secret
# fields blank, so the demo uses each CLI's ambient session. Re-run with --force to
# overwrite an existing credentials.yaml.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/config.sh"; source "$HERE/lib.sh"
set +e   # detection commands are allowed to fail; we report and continue

OUT="${CASK_CREDENTIALS_OUT:-$DEMO_DIR/credentials.yaml}"
FORCE=0; [ "${1:-}" = "--force" ] && FORCE=1
if [ -f "$OUT" ] && [ "$FORCE" -eq 0 ]; then
  die "$OUT already exists — inspect it, or re-run with --force to overwrite"
fi
note() { printf '     %s\n' "$*"; }

# --- GCP: active project ------------------------------------------------------
gcp_project=""
if gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
  gcp_project="$(gcloud config get-value project 2>/dev/null)"
  [ "$gcp_project" = "(unset)" ] && gcp_project=""
  [ -z "$gcp_project" ] && gcp_project="$(gcloud projects list --format='value(projectId)' --limit=1 2>/dev/null)"
  if [ -n "$gcp_project" ]; then ok "gcp: project $gcp_project"
  else warn "gcp: authenticated but no project (set: gcloud config set project <id>)"; fi
else
  warn "gcp: not authenticated (run: gcloud auth login)"
fi

# --- AWS: caller + region -----------------------------------------------------
aws_region=""
if arn="$(aws sts get-caller-identity --query Arn --output text 2>/dev/null)"; then
  aws_region="$(aws configure get region 2>/dev/null)"
  [ -z "$aws_region" ] && aws_region="${AWS_REGION:-us-east-1}"
  ok "aws: $arn (region $aws_region)"
else
  warn "aws: not authenticated (run: aws configure)"
fi

# --- OCI: tenancy(=root compartment) + region from the active config ----------
oci_compartment=""; oci_region=""
if oci iam region list >/dev/null 2>&1; then
  oci_cfg="${OCI_CLI_CONFIG_FILE:-$HOME/.oci/config}"
  if [ -f "$oci_cfg" ]; then
    oci_compartment="$(awk -F= '/^\[DEFAULT\]/{f=1;next} /^\[/{f=0} f&&$1=="tenancy"{gsub(/ /,"");print $2;exit}' "$oci_cfg")"
    oci_region="$(awk -F= '/^\[DEFAULT\]/{f=1;next} /^\[/{f=0} f&&$1=="region"{gsub(/ /,"");print $2;exit}' "$oci_cfg")"
  fi
  [ -z "$oci_region" ] && oci_region="${OCI_REGION:-}"
  if [ -n "$oci_compartment" ]; then
    ok "oci: compartment (root/tenancy) $oci_compartment  region ${oci_region:-<unknown>}"
    note "to use a sub-compartment instead, pick an id below and edit credentials.yaml:"
    oci iam compartment list --compartment-id "$oci_compartment" \
      --query 'data[].{name:name,id:id}' --output table 2>/dev/null || true
  else
    warn "oci: authenticated but couldn't read tenancy from $oci_cfg"
  fi
else
  warn "oci: not authenticated (run: oci setup bootstrap)"
fi

# --- write --------------------------------------------------------------------
( umask 077
cat > "$OUT" <<EOF
# Generated by demo/init-credentials.sh from your authenticated cloud CLIs.
# Ambient auth: secret fields are intentionally blank (each CLI uses its own login).
# Fill a blank id below if its cloud wasn't authenticated when this ran.

gcp:
  project: "${gcp_project}"
  service_account_key: ""

oci:
  compartment: "${oci_compartment}"
  region: "${oci_region}"
  subnet: ""
  tenancy: ""
  user: ""
  fingerprint: ""
  key_file: ""

aws:
  region: "${aws_region}"
  access_key_id: ""
  secret_access_key: ""
EOF
)
echo
ok "wrote $OUT"
note "review it, then run: demo/preflight.sh"
